import { defineConfig } from '@chakra-ui/react';

export default defineConfig({
	theme: {
		tokens: {
			colors: {
				accent: {
					100: { value: '#ddccbd' },
					200: { value: '#ffd5b2' },
					300: { value: '#f9caa2' },
					500: { value: '#94481c' },
					700: { value: '#ae7f5f' },
				},
				'typography.base': { value: '#000' },
				'typography.secondary': { value: '#4e3a0c' },
				'typography.inverted': { value: '#fff' },
				'selection.foreground': { value: '#000' },
				'selection.background': { value: '#ffca9b' },
				'highlight.foreground': { value: '#000' },
				'highlight.background': { value: '#ffba7d' },
				'surface.background': { value: '#fffaf3' },
				'surface.invertedBackground': { value: '#000' },
				'surface.panel': { value: '#f8f2e9' },
				'surface.border': { value: '#e0d6c7' },
				'dim.50': { value: '#d6ab7d10' },
				'dim.100': { value: '#d6ab7d17' },
				'dim.200': { value: '#d6ab7d25' },
				'dim.400': { value: '#d6ab7d3c' },
				'dim.500': { value: '#d6ab7d3c' },
				'overlay.500': { value: '#00000075' },
				'message.error': { value: '#b30606' },
				'message.success': { value: '#3ea863' },
			},
			shadows: {
				input: { value: '0 0 0 3px #ffd5b2' },
				outline: { value: '0 0 0 3px #ffd5b2' },
			},
		},
		semanticTokens: {
			colors: {
				'link.base': { value: '{colors.accent.500}' },
				'link.hover': { value: '{colors.accent.700}' },
				'typography.accent': { value: '{colors.accent.500}' },
				'control.base.background': { value: '{colors.dim.200}' },
				'control.base.foreground': { value: '{colors.typography.base}' },
				'control.base.active.background': { value: '{colors.dim.400}' },
				'control.base.disabled.background': { value: '{colors.dim.100}' },
				'control.action.foreground': { value: '{colors.accent.500}' },
				'control.action.background': { value: '{colors.accent.200}' },
				'control.action.active.background': { value: '{colors.accent.300}' },
				'control.input.background': { value: '{colors.dim.200}' },
				'control.input.border': { value: 'transparent' },
				'control.input.active.border': { value: '{colors.dim.500}' },
				'control.ghost.foreground': { value: '{colors.typography.base}' },
				'control.ghost.background': { value: 'transparent' },
				'control.ghost.hover.foreground': {
					value: '{colors.typography.base}',
				},
				'control.ghost.hover.background': { value: '{colors.dim.400}' },
				'control.ghost.active.foreground': {
					value: '{colors.typography.base}',
				},
				'control.ghost.active.background': { value: '{colors.dim.400}' },
				'control.option.foreground': { value: '{colors.typography.base}' },
				'control.option.background': { value: 'transparent' },
				'control.option.hover.foreground': {
					value: '{colors.typography.base}',
				},
				'control.option.hover.background': { value: '{colors.dim.400}' },
				'control.option.active.foreground': {
					value: '{colors.typography.base}',
				},
				'control.option.active.background': { value: '{colors.dim.400}' },
				'container.head.foreground': { value: '{colors.typography.base}' },
				'container.head.background': { value: '{colors.surface.panel}' },
				'container.message.foreground': { value: '{colors.typography.base}' },
				'container.message.background': { value: '{colors.dim.100}' },
				'code.token.comment': { value: '#a5674e' },
				'code.token.punctuation': { value: '#9c5f1c' },
				'code.token.property': { value: '#ac4e04' },
				'code.token.selector': { value: '#ac4e04' },
				'code.token.operator': { value: '#e14e12' },
				'code.token.attr': { value: '#bf3903' },
				'code.token.variable': { value: '#d46f0f' },
				'code.token.function': { value: '#d46f0f' },
				'scheme.alert.text': { value: '#fff' },
				'scheme.alert.base': { value: '#C53030' },
				'scheme.alert.hover': { value: '#9B2C2C' },
			},
		},
	},
});
